server:
  port: 8700
#  servlet:
#    context-path: /${spring.application.name}
spring:
  application:
    name: bg-tsf
#  profiles:
#    active: soho



logging:
  file: /logs/${spring.application.name}/root.log
  level:
    root: INFO
#logging:
#  config: classpath:${spring.profiles.active}/logback-${spring.profiles.active}.xml
management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
      path-mapping:
        shutdown: shutdown


#management:
#  security:
#    enabled: false
tct:
  enabled: false
feign:
  tsf:
    enabled: true